/* automatically generated by 'generate_test.py' */
void test_back_propagation()
{
    int ndims[] = {2, 3, 4};
    Network network = network_create(3, ndims);

    // fill network
    network.weights[1][0 * 2 + 0 * 1] = 0.4900934100151062;
    network.weights[1][0 * 2 + 1 * 1] = 0.8964447379112244;
    network.weights[1][1 * 2 + 0 * 1] = 0.455627977848053;
    network.weights[1][1 * 2 + 1 * 1] = 0.6323062777519226;
    network.weights[1][2 * 2 + 0 * 1] = 0.3488934636116028;
    network.weights[1][2 * 2 + 1 * 1] = 0.40171730518341064;
    network.weights[2][0 * 3 + 0 * 1] = 0.022325754165649414;
    network.weights[2][0 * 3 + 1 * 1] = 0.16885894536972046;
    network.weights[2][0 * 3 + 2 * 1] = 0.2938884496688843;
    network.weights[2][1 * 3 + 0 * 1] = 0.518521785736084;
    network.weights[2][1 * 3 + 1 * 1] = 0.6976675987243652;
    network.weights[2][1 * 3 + 2 * 1] = 0.800011396408081;
    network.weights[2][2 * 3 + 0 * 1] = 0.16102945804595947;
    network.weights[2][2 * 3 + 1 * 1] = 0.28226858377456665;
    network.weights[2][2 * 3 + 2 * 1] = 0.6816085577011108;
    network.weights[2][3 * 3 + 0 * 1] = 0.9151939749717712;
    network.weights[2][3 * 3 + 1 * 1] = 0.39709991216659546;
    network.weights[2][3 * 3 + 2 * 1] = 0.8741558790206909;
    network.biases[1][0 * 1] = 0.41940832138061523;
    network.biases[1][1 * 1] = 0.5529070496559143;
    network.biases[1][2 * 1] = 0.9527381062507629;
    network.biases[2][0 * 1] = 0.036164820194244385;
    network.biases[2][1 * 1] = 0.1852310299873352;
    network.biases[2][2 * 1] = 0.37341737747192383;
    network.biases[2][3 * 1] = 0.3051000237464905;

    // fill gradients
    double *nabla_w1 = malloc(6 * sizeof(double));
    nabla_w1[0 * 2 + 0 * 1] = 0.013823913410305977;
    nabla_w1[0 * 2 + 1 * 1] = 0.021399881690740585;
    nabla_w1[1 * 2 + 0 * 1] = 0.019749242812395096;
    nabla_w1[1 * 2 + 1 * 1] = 0.03057248890399933;
    nabla_w1[2 * 2 + 0 * 1] = 0.02851865626871586;
    nabla_w1[2 * 2 + 1 * 1] = 0.044147834181785583;
    double *nabla_b1 = malloc(3 * sizeof(double));
    nabla_b1[0 * 1] = 0.027856383472681046;
    nabla_b1[1 * 1] = 0.039796434342861176;
    nabla_b1[2 * 1] = 0.05746756121516228;
    double *nabla_w2 = malloc(12 * sizeof(double));
    nabla_w2[0 * 3 + 0 * 1] = 0.19593028724193573;
    nabla_w2[0 * 3 + 1 * 1] = 0.19235506653785706;
    nabla_w2[0 * 3 + 2 * 1] = 0.19920076429843903;
    nabla_w2[1 * 3 + 0 * 1] = 0.14140258729457855;
    nabla_w2[1 * 3 + 1 * 1] = 0.13882236182689667;
    nabla_w2[1 * 3 + 2 * 1] = 0.14376288652420044;
    nabla_w2[2 * 3 + 0 * 1] = 0.12867256999015808;
    nabla_w2[2 * 3 + 1 * 1] = 0.1263246238231659;
    nabla_w2[2 * 3 + 2 * 1] = 0.1308203786611557;
    nabla_w2[3 * 3 + 0 * 1] = 0.04046597331762314;
    nabla_w2[3 * 3 + 1 * 1] = 0.03972757235169411;
    nabla_w2[3 * 3 + 2 * 1] = 0.041141435503959656;
    double *nabla_b2 = malloc(4 * sizeof(double));
    nabla_b2[0 * 1] = 0.24665787816047668;
    nabla_b2[1 * 1] = 0.17801262438297272;
    nabla_b2[2 * 1] = 0.16198670864105225;
    nabla_b2[3 * 1] = 0.05094287171959877;

    // fill inputs and label
    double *inputs = malloc(2 * sizeof(double));
    inputs[0 * 1] = 0.49625658988952637;
    inputs[1 * 1] = 0.7682217955589294;
    double *label = malloc(4 * sizeof(double));
    label[0 * 1] = 0.08847743272781372;
    label[1 * 1] = 0.13203048706054688;
    label[2 * 1] = 0.30742281675338745;
    label[3 * 1] = 0.6340786814689636;

    // run backprop
    forward(network, inputs);
    double loss = compute_loss(network, label);
    backward(network, label);
    // compare loss
    assert_scalar("loss", 1.078608512878418, loss);

    // compare gradients
    assert_array("nabla_w1", 6, nabla_w1, network.weights_grad[1]);
    assert_array("nabla_b1", 3, nabla_b1, network.biases_grad[1]);
    assert_array("nabla_w2", 12, nabla_w2, network.weights_grad[2]);
    assert_array("nabla_b2", 4, nabla_b2, network.biases_grad[2]);

    // free gradients
    free(nabla_w1);
    free(nabla_b1);
    free(nabla_w2);
    free(nabla_b2);
    // free inputs and labels
    free(inputs);
    free(label);
    // destroy network
    network_destroy(network);
}
